AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 101
Naming/FileName:
  Exclude:
    - 'lib/omniauth-vkontakte.rb'
