AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/omniauth-vkontakte.rb'
