language: ruby
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system
  - gem --version
rvm:
  - 3.0.0
  - 2.7.2
  - 2.6.6
  - jruby-head
script:
  - bundle exec rspec
  - bundle exec rubocop
